import type jsPDF from "jspdf";
import logoMark from "@/assets/talenval-logo.png";
import { supabase } from "@/integrations/supabase/client";

// Cached branding for PDF reports: Talenval logo + the signed-in HR's company name.
let logoData: string | null = null;
let companyName = "";

async function preload() {
  if (typeof window === "undefined") return;
  try {
    const blob = await (await fetch(logoMark)).blob();
    logoData = await new Promise<string>((res, rej) => {
      const r = new FileReader();
      r.onload = () => res(String(r.result));
      r.onerror = rej;
      r.readAsDataURL(blob);
    });
  } catch { /* logo optional */ }
  try {
    const { data: u } = await supabase.auth.getUser();
    if (u.user) {
      const { data } = await supabase.from("profiles").select("company_name").eq("id", u.user.id).maybeSingle();
      companyName = data?.company_name ?? "";
    }
  } catch { /* name optional */ }
}
void preload();

/** Draws the branded header band; returns the y position to continue from. */
export function drawBrandHeader(doc: jsPDF, title: string, company?: string | null) {
  const w = doc.internal.pageSize.getWidth();
  const name = (company || companyName || "").trim();
  doc.setFillColor(11, 31, 77);
  doc.rect(0, 0, w, 64, "F");
  if (logoData) doc.addImage(logoData, "PNG", 40, 12, 40, 40);
  doc.setTextColor(255);
  doc.setFontSize(15);
  doc.text(name || "Talenval", 90, 32);
  doc.setFontSize(9);
  doc.setTextColor(180, 220, 200);
  doc.text(name ? "Hiring report · powered by Talenval" : "Talent + Evaluation", 90, 47);
  doc.setTextColor(255);
  doc.setFontSize(10);
  doc.text("CONFIDENTIAL", w - 40, 36, { align: "right" });
  doc.setTextColor(0);
  doc.setFontSize(17);
  doc.text(title, 40, 94);
  return 112;
}

/** Adds a footer with company name and page numbers on every page. */
export function drawBrandFooters(doc: jsPDF, company?: string | null) {
  const name = (company || companyName || "").trim();
  const n = doc.getNumberOfPages();
  const w = doc.internal.pageSize.getWidth();
  const h = doc.internal.pageSize.getHeight();
  for (let i = 1; i <= n; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setTextColor(120);
    doc.text(`${name ? `${name} · ` : ""}Confidential candidate report · Generated by Talenval`, 40, h - 20);
    doc.text(`Page ${i} of ${n}`, w - 40, h - 20, { align: "right" });
  }
  doc.setTextColor(0);
}
