/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as ApiDocsRouteImport } from './routes/api-docs'
import { Route as AssessmentsRouteImport } from './routes/assessments'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as CareersPageRouteImport } from './routes/careers-page'
import { Route as DemoRouteImport } from './routes/demo'
import { Route as DevelopersRouteImport } from './routes/developers'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as InterviewsRouteImport } from './routes/interviews'
import { Route as OffersRouteImport } from './routes/offers'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as PipelineRouteImport } from './routes/pipeline'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as SearchRouteImport } from './routes/search'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AssessmentTokenRouteImport } from './routes/assessment/$token'
import { Route as CareersSlugRouteImport } from './routes/careers/$slug'
import { Route as DossierTokenRouteImport } from './routes/dossier/$token'
import { Route as InterviewTokenRouteImport } from './routes/interview/$token'
import { Route as JobsIndexRouteImport } from './routes/jobs/index'
import { Route as JobsIdRouteImport } from './routes/jobs/$id'
import { Route as PaymentVerifyRouteImport } from './routes/payment/verify'
import { Route as AdminUsersIdRouteImport } from './routes/admin/users/$id'
import { Route as LovableEmailAuthPreviewRouteImport } from './routes/lovable/email/auth/preview'
import { Route as LovableEmailAuthWebhookRouteImport } from './routes/lovable/email/auth/webhook'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDocsRoute = ApiDocsRouteImport.update({
  id: '/api-docs',
  path: '/api-docs',
  getParentRoute: () => rootRouteImport,
} as any)
const AssessmentsRoute = AssessmentsRouteImport.update({
  id: '/assessments',
  path: '/assessments',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CareersPageRoute = CareersPageRouteImport.update({
  id: '/careers-page',
  path: '/careers-page',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoRoute = DemoRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => rootRouteImport,
} as any)
const DevelopersRoute = DevelopersRouteImport.update({
  id: '/developers',
  path: '/developers',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const InterviewsRoute = InterviewsRouteImport.update({
  id: '/interviews',
  path: '/interviews',
  getParentRoute: () => rootRouteImport,
} as any)
const OffersRoute = OffersRouteImport.update({
  id: '/offers',
  path: '/offers',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const PipelineRoute = PipelineRouteImport.update({
  id: '/pipeline',
  path: '/pipeline',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AssessmentTokenRoute = AssessmentTokenRouteImport.update({
  id: '/assessment/$token',
  path: '/assessment/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const CareersSlugRoute = CareersSlugRouteImport.update({
  id: '/careers/$slug',
  path: '/careers/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const DossierTokenRoute = DossierTokenRouteImport.update({
  id: '/dossier/$token',
  path: '/dossier/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const InterviewTokenRoute = InterviewTokenRouteImport.update({
  id: '/interview/$token',
  path: '/interview/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsIndexRoute = JobsIndexRouteImport.update({
  id: '/jobs/',
  path: '/jobs/',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsIdRoute = JobsIdRouteImport.update({
  id: '/jobs/$id',
  path: '/jobs/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentVerifyRoute = PaymentVerifyRouteImport.update({
  id: '/payment/verify',
  path: '/payment/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersIdRoute = AdminUsersIdRouteImport.update({
  id: '/admin/users/$id',
  path: '/admin/users/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailAuthPreviewRoute = LovableEmailAuthPreviewRouteImport.update({
  id: '/lovable/email/auth/preview',
  path: '/lovable/email/auth/preview',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailAuthWebhookRoute = LovableEmailAuthWebhookRouteImport.update({
  id: '/lovable/email/auth/webhook',
  path: '/lovable/email/auth/webhook',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/api-docs': typeof ApiDocsRoute
  '/assessments': typeof AssessmentsRoute
  '/auth': typeof AuthRoute
  '/careers-page': typeof CareersPageRoute
  '/demo': typeof DemoRoute
  '/developers': typeof DevelopersRoute
  '/faq': typeof FaqRoute
  '/interviews': typeof InterviewsRoute
  '/offers': typeof OffersRoute
  '/onboarding': typeof OnboardingRoute
  '/pipeline': typeof PipelineRoute
  '/pricing': typeof PricingRoute
  '/search': typeof SearchRoute
  '/assessment/$token': typeof AssessmentTokenRoute
  '/careers/$slug': typeof CareersSlugRoute
  '/dossier/$token': typeof DossierTokenRoute
  '/interview/$token': typeof InterviewTokenRoute
  '/jobs/$id': typeof JobsIdRoute
  '/payment/verify': typeof PaymentVerifyRoute
  '/admin/': typeof AdminIndexRoute
  '/jobs/': typeof JobsIndexRoute
  '/admin/users/$id': typeof AdminUsersIdRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/api-docs': typeof ApiDocsRoute
  '/assessments': typeof AssessmentsRoute
  '/auth': typeof AuthRoute
  '/careers-page': typeof CareersPageRoute
  '/demo': typeof DemoRoute
  '/developers': typeof DevelopersRoute
  '/faq': typeof FaqRoute
  '/interviews': typeof InterviewsRoute
  '/offers': typeof OffersRoute
  '/onboarding': typeof OnboardingRoute
  '/pipeline': typeof PipelineRoute
  '/pricing': typeof PricingRoute
  '/search': typeof SearchRoute
  '/assessment/$token': typeof AssessmentTokenRoute
  '/careers/$slug': typeof CareersSlugRoute
  '/dossier/$token': typeof DossierTokenRoute
  '/interview/$token': typeof InterviewTokenRoute
  '/jobs/$id': typeof JobsIdRoute
  '/payment/verify': typeof PaymentVerifyRoute
  '/admin': typeof AdminIndexRoute
  '/jobs': typeof JobsIndexRoute
  '/admin/users/$id': typeof AdminUsersIdRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/api-docs': typeof ApiDocsRoute
  '/assessments': typeof AssessmentsRoute
  '/auth': typeof AuthRoute
  '/careers-page': typeof CareersPageRoute
  '/demo': typeof DemoRoute
  '/developers': typeof DevelopersRoute
  '/faq': typeof FaqRoute
  '/interviews': typeof InterviewsRoute
  '/offers': typeof OffersRoute
  '/onboarding': typeof OnboardingRoute
  '/pipeline': typeof PipelineRoute
  '/pricing': typeof PricingRoute
  '/search': typeof SearchRoute
  '/assessment/$token': typeof AssessmentTokenRoute
  '/careers/$slug': typeof CareersSlugRoute
  '/dossier/$token': typeof DossierTokenRoute
  '/interview/$token': typeof InterviewTokenRoute
  '/jobs/$id': typeof JobsIdRoute
  '/payment/verify': typeof PaymentVerifyRoute
  '/admin/': typeof AdminIndexRoute
  '/jobs/': typeof JobsIndexRoute
  '/admin/users/$id': typeof AdminUsersIdRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/api-docs'
    | '/assessments'
    | '/auth'
    | '/careers-page'
    | '/demo'
    | '/developers'
    | '/faq'
    | '/interviews'
    | '/offers'
    | '/onboarding'
    | '/pipeline'
    | '/pricing'
    | '/search'
    | '/assessment/$token'
    | '/careers/$slug'
    | '/dossier/$token'
    | '/interview/$token'
    | '/jobs/$id'
    | '/payment/verify'
    | '/admin/'
    | '/jobs/'
    | '/admin/users/$id'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/api-docs'
    | '/assessments'
    | '/auth'
    | '/careers-page'
    | '/demo'
    | '/developers'
    | '/faq'
    | '/interviews'
    | '/offers'
    | '/onboarding'
    | '/pipeline'
    | '/pricing'
    | '/search'
    | '/assessment/$token'
    | '/careers/$slug'
    | '/dossier/$token'
    | '/interview/$token'
    | '/jobs/$id'
    | '/payment/verify'
    | '/admin'
    | '/jobs'
    | '/admin/users/$id'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/api-docs'
    | '/assessments'
    | '/auth'
    | '/careers-page'
    | '/demo'
    | '/developers'
    | '/faq'
    | '/interviews'
    | '/offers'
    | '/onboarding'
    | '/pipeline'
    | '/pricing'
    | '/search'
    | '/assessment/$token'
    | '/careers/$slug'
    | '/dossier/$token'
    | '/interview/$token'
    | '/jobs/$id'
    | '/payment/verify'
    | '/admin/'
    | '/jobs/'
    | '/admin/users/$id'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ApiDocsRoute: typeof ApiDocsRoute
  AssessmentsRoute: typeof AssessmentsRoute
  AuthRoute: typeof AuthRoute
  CareersPageRoute: typeof CareersPageRoute
  DemoRoute: typeof DemoRoute
  DevelopersRoute: typeof DevelopersRoute
  FaqRoute: typeof FaqRoute
  InterviewsRoute: typeof InterviewsRoute
  OffersRoute: typeof OffersRoute
  OnboardingRoute: typeof OnboardingRoute
  PipelineRoute: typeof PipelineRoute
  PricingRoute: typeof PricingRoute
  SearchRoute: typeof SearchRoute
  AssessmentTokenRoute: typeof AssessmentTokenRoute
  CareersSlugRoute: typeof CareersSlugRoute
  DossierTokenRoute: typeof DossierTokenRoute
  InterviewTokenRoute: typeof InterviewTokenRoute
  JobsIdRoute: typeof JobsIdRoute
  PaymentVerifyRoute: typeof PaymentVerifyRoute
  AdminIndexRoute: typeof AdminIndexRoute
  JobsIndexRoute: typeof JobsIndexRoute
  AdminUsersIdRoute: typeof AdminUsersIdRoute
  LovableEmailAuthPreviewRoute: typeof LovableEmailAuthPreviewRoute
  LovableEmailAuthWebhookRoute: typeof LovableEmailAuthWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api-docs': {
      id: '/api-docs'
      path: '/api-docs'
      fullPath: '/api-docs'
      preLoaderRoute: typeof ApiDocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assessments': {
      id: '/assessments'
      path: '/assessments'
      fullPath: '/assessments'
      preLoaderRoute: typeof AssessmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/careers-page': {
      id: '/careers-page'
      path: '/careers-page'
      fullPath: '/careers-page'
      preLoaderRoute: typeof CareersPageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo': {
      id: '/demo'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof DemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/developers': {
      id: '/developers'
      path: '/developers'
      fullPath: '/developers'
      preLoaderRoute: typeof DevelopersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/interviews': {
      id: '/interviews'
      path: '/interviews'
      fullPath: '/interviews'
      preLoaderRoute: typeof InterviewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/offers': {
      id: '/offers'
      path: '/offers'
      fullPath: '/offers'
      preLoaderRoute: typeof OffersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pipeline': {
      id: '/pipeline'
      path: '/pipeline'
      fullPath: '/pipeline'
      preLoaderRoute: typeof PipelineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assessment/$token': {
      id: '/assessment/$token'
      path: '/assessment/$token'
      fullPath: '/assessment/$token'
      preLoaderRoute: typeof AssessmentTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/careers/$slug': {
      id: '/careers/$slug'
      path: '/careers/$slug'
      fullPath: '/careers/$slug'
      preLoaderRoute: typeof CareersSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dossier/$token': {
      id: '/dossier/$token'
      path: '/dossier/$token'
      fullPath: '/dossier/$token'
      preLoaderRoute: typeof DossierTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/interview/$token': {
      id: '/interview/$token'
      path: '/interview/$token'
      fullPath: '/interview/$token'
      preLoaderRoute: typeof InterviewTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs/': {
      id: '/jobs/'
      path: '/jobs'
      fullPath: '/jobs/'
      preLoaderRoute: typeof JobsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs/$id': {
      id: '/jobs/$id'
      path: '/jobs/$id'
      fullPath: '/jobs/$id'
      preLoaderRoute: typeof JobsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment/verify': {
      id: '/payment/verify'
      path: '/payment/verify'
      fullPath: '/payment/verify'
      preLoaderRoute: typeof PaymentVerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users/$id': {
      id: '/admin/users/$id'
      path: '/admin/users/$id'
      fullPath: '/admin/users/$id'
      preLoaderRoute: typeof AdminUsersIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/preview': {
      id: '/lovable/email/auth/preview'
      path: '/lovable/email/auth/preview'
      fullPath: '/lovable/email/auth/preview'
      preLoaderRoute: typeof LovableEmailAuthPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/webhook': {
      id: '/lovable/email/auth/webhook'
      path: '/lovable/email/auth/webhook'
      fullPath: '/lovable/email/auth/webhook'
      preLoaderRoute: typeof LovableEmailAuthWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ApiDocsRoute: ApiDocsRoute,
  AssessmentsRoute: AssessmentsRoute,
  AuthRoute: AuthRoute,
  CareersPageRoute: CareersPageRoute,
  DemoRoute: DemoRoute,
  DevelopersRoute: DevelopersRoute,
  FaqRoute: FaqRoute,
  InterviewsRoute: InterviewsRoute,
  OffersRoute: OffersRoute,
  OnboardingRoute: OnboardingRoute,
  PipelineRoute: PipelineRoute,
  PricingRoute: PricingRoute,
  SearchRoute: SearchRoute,
  AssessmentTokenRoute: AssessmentTokenRoute,
  CareersSlugRoute: CareersSlugRoute,
  DossierTokenRoute: DossierTokenRoute,
  InterviewTokenRoute: InterviewTokenRoute,
  JobsIdRoute: JobsIdRoute,
  PaymentVerifyRoute: PaymentVerifyRoute,
  AdminIndexRoute: AdminIndexRoute,
  JobsIndexRoute: JobsIndexRoute,
  AdminUsersIdRoute: AdminUsersIdRoute,
  LovableEmailAuthPreviewRoute: LovableEmailAuthPreviewRoute,
  LovableEmailAuthWebhookRoute: LovableEmailAuthWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
