INSERT INTO public.skill_tests (slug, title, category, skill_area, description, difficulty, duration_minutes, question_count, proctored, tags, is_active)
SELECT
  'oilfield-' || regexp_replace(lower(area), '[^a-z0-9]+', '-', 'g'),
  area || ' Competency Test',
  'role_specific',
  area,
  'Validated oilfield competency assessment for ' || area || ' roles, covering safety-critical procedures, equipment knowledge, industry standards and field judgement.',
  diff,
  30,
  15,
  true,
  ARRAY['oilfield','energy','role', area],
  true
FROM (VALUES
  ('Drilling Engineer','advanced'),
  ('Drilling Supervisor / Toolpusher','advanced'),
  ('Directional Driller','advanced'),
  ('Mud Logger','intermediate'),
  ('Drilling Fluids (Mud) Engineer','intermediate'),
  ('Well Control (IWCF Style)','advanced'),
  ('Wellsite Geologist','advanced'),
  ('Petroleum Engineer','advanced'),
  ('Reservoir Engineer','advanced'),
  ('Production Engineer','advanced'),
  ('Completion Engineer','advanced'),
  ('Workover / Well Intervention Specialist','intermediate'),
  ('Coiled Tubing Operator','intermediate'),
  ('Wireline Operator','intermediate'),
  ('Slickline Operator','intermediate'),
  ('Cementing Engineer','intermediate'),
  ('Hydraulic Fracturing Engineer','advanced'),
  ('Snubbing Supervisor','advanced'),
  ('Subsea Engineer','advanced'),
  ('ROV Pilot Technician','intermediate'),
  ('Offshore Installation Manager','advanced'),
  ('Dynamic Positioning Operator','advanced'),
  ('Marine / Barge Engineer','intermediate'),
  ('Pipeline Engineer','intermediate'),
  ('Pipeline Integrity / Corrosion Engineer','advanced'),
  ('Process Engineer (Oil & Gas)','advanced'),
  ('Facilities Engineer','intermediate'),
  ('Instrumentation & Control Technician','intermediate'),
  ('Electrical Technician (Hazardous Areas)','intermediate'),
  ('Mechanical Maintenance Technician','intermediate'),
  ('Rotating Equipment Engineer','advanced'),
  ('HSE Officer (Oil & Gas)','intermediate'),
  ('Permit to Work Coordinator','intermediate'),
  ('Environmental Compliance Officer','intermediate'),
  ('Rig Electrician','intermediate'),
  ('Rig Mechanic','intermediate'),
  ('Crane Operator (Offshore)','intermediate'),
  ('Derrickman','beginner'),
  ('Roughneck / Floorhand','beginner'),
  ('Materials & Logistics Coordinator (Oilfield)','intermediate'),
  ('Petrophysicist','advanced'),
  ('Geophysicist (Seismic Interpretation)','advanced'),
  ('LNG Plant Operator','intermediate'),
  ('Refinery Operations Technician','intermediate'),
  ('Oil & Gas Procurement / Contracts Specialist','intermediate'),
  ('QA/QC Inspector (Welding & NDT)','advanced')
) AS t(area, diff)
WHERE NOT EXISTS (
  SELECT 1 FROM public.skill_tests s
  WHERE s.slug = 'oilfield-' || regexp_replace(lower(t.area), '[^a-z0-9]+', '-', 'g')
);